[CmdletBinding()]
param([Parameter(Mandatory)][string]$BindingPath)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
. 'C:\FPGA\V41_NVP_R1H_BRAM_BACKED_LARGE_SAMPLE\09_HOST_TOOLS\R1hCampaignCommon.ps1'
function Value([string]$text,[string]$key){$m=[regex]::Matches($text,'(?m)^'+[regex]::Escape($key)+'=([^\r\n]*)\r?$');if($m.Count-ne1){throw "$key exact-line count is $($m.Count)"};$m[0].Groups[1].Value}
$binding=Get-R1hBindingDocument -BindingPath $BindingPath;$baselinePath=Join-Path $script:R1hPrecheckRoot 'R1H_HOST_BASELINE_GATE.txt';$jtagPath=Join-Path $script:R1hPrecheckRoot 'R1H_START_JTAG_DONE_GATE.txt';$safetyPath=Join-Path $script:R1hPrecheckRoot 'R1H_START_SAFETY_GATE.txt';$out=Join-Path $script:R1hPrecheckRoot 'R1H_FRESH_FORMAL_START_GATE.txt';if(Test-Path -LiteralPath $out){throw 'refusing to overwrite fresh formal-start gate'};$baseline=[IO.File]::ReadAllText($baselinePath);$jtag=[IO.File]::ReadAllText($jtagPath);$safety=[IO.File]::ReadAllText($safetyPath);if((Value $baseline R1H_HOST_BASELINE)-cne'PASS_2_OF_2'-or(Value $jtag R1H_START_JTAG_GATE)-cne'PASS_5_OF_5'){throw 'baseline/JTAG gate failed'};$safetyGate=Value $safety R1H_START_SAFETY_GATE
if($safetyGate-ceq'PASS_SAFE_BOOTSTRAP_REQUIRED'){Write-R1hUtf8NoBom -Path $out -Lines @('FORMAL_START_GATE=BOOTSTRAP_REQUIRED_SAFE','BOOTSTRAP_REQUIRED=YES','READ_ONLY_GATE=YES',"R1H_FULL_JTAG_TARGET_PATH=$([string]$binding.selectedFullJtagTargetPath)","BASELINE_SHA256=$((Get-FileHash -Algorithm SHA256 -LiteralPath $baselinePath).Hash)","JTAG_SHA256=$((Get-FileHash -Algorithm SHA256 -LiteralPath $jtagPath).Hash)","SAFETY_SHA256=$((Get-FileHash -Algorithm SHA256 -LiteralPath $safetyPath).Hash)");Get-Content -LiteralPath $out;exit 0}
if($safetyGate-cne'PASS_EXISTING_FORMAL_INFRA_CANDIDATE'){throw 'unsafe or unclassified start safety gate'};$telemetry=Join-Path $script:R1hPrecheckRoot 'EXISTING_FORMAL_TELEMETRY.log';$telemetryText=[IO.File]::ReadAllText($telemetry);if((Value $telemetryText RESULT)-cne'PASS'-or(Value $telemetryText READ_ONLY)-cne'YES'-or(Value $telemetryText STATIC_SNAPSHOTS_MATCH)-cne'YES'){throw 'formal telemetry gate failed'}
Write-R1hUtf8NoBom -Path $out -Lines @('FORMAL_START_GATE=PASS_EXISTING_EXACT_FORMAL','KERNEL=7.0.0-29-generic','NEXT_REBOOT_KERNEL=7.0.0-29-generic',"BOOT_ID=$(Value $baseline R1H_BOOT_ID_BASELINE)",'ENDPOINT_COUNT=1','ENDPOINT_IDENTITY=10ee:7011/subsystem_0007/class_058000','LINK=GEN1_X1','BAR0_BYTES=131072','BAR1_BYTES=65536','PINNED_DRIVER=PASS','FORMAL_IDENTITY=A40A0C07/0000400B/00031002','DIAGNOSTIC_MAGIC=0','NODE_OWNERS=0','TASK_DMA=0','KERNEL_AER_HEALTH=PASS','SELECTED_JTAG=Xilinx/80802026a98b01',"R1H_FULL_JTAG_TARGET_PATH=$([string]$binding.selectedFullJtagTargetPath)",'FPGA_PART=xc7a35t','FPGA_IDCODE=0362D093','DONE=1','JTAG_FREQUENCY_CHANGED=NO','READ_ONLY_GATE=YES','BOOTSTRAP_REQUIRED=NO',"BASELINE_SHA256=$((Get-FileHash -Algorithm SHA256 -LiteralPath $baselinePath).Hash)","JTAG_SHA256=$((Get-FileHash -Algorithm SHA256 -LiteralPath $jtagPath).Hash)","SAFETY_SHA256=$((Get-FileHash -Algorithm SHA256 -LiteralPath $safetyPath).Hash)","TELEMETRY_SHA256=$((Get-FileHash -Algorithm SHA256 -LiteralPath $telemetry).Hash)");Get-Content -LiteralPath $out
