[CmdletBinding()]
param([Parameter(Mandatory)][string]$BindingPath)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
. 'C:\FPGA\V41_NVP_R1H_BRAM_BACKED_LARGE_SAMPLE\09_HOST_TOOLS\R1hCampaignCommon.ps1'
function Gzip64([byte[]]$b){$m=[IO.MemoryStream]::new();try{$g=[IO.Compression.GzipStream]::new($m,[IO.Compression.CompressionLevel]::Optimal,$true);try{$g.Write($b,0,$b.Length)}finally{$g.Dispose()};[Convert]::ToBase64String($m.ToArray())}finally{$m.Dispose()}}
function Value([string]$text,[string]$key){$m=[regex]::Matches($text,'(?m)^'+[regex]::Escape($key)+'=([^\r\n]*)\r?$');if($m.Count-ne1){throw "$key exact-line count is $($m.Count)"};$m[0].Groups[1].Value}
$binding=Get-R1hBindingDocument -BindingPath $BindingPath;Assert-R1hAcceptedToolSet;$safety=[IO.File]::ReadAllText((Join-Path $script:R1hPrecheckRoot 'R1H_START_SAFETY_GATE.txt'));if((Value $safety R1H_START_SAFETY_GATE)-cne'PASS_EXISTING_FORMAL_INFRA_CANDIDATE'){throw 'existing-formal telemetry is permitted only for the exact infrastructure candidate'}
$out=Join-Path $script:R1hPrecheckRoot 'EXISTING_FORMAL_TELEMETRY.log';if(Test-Path -LiteralPath $out){throw 'refusing to overwrite existing-formal telemetry'};$remoteOut='/home/vcdeagent1/FPGA_AHD_HOST/v41_nvp_r1h/existing_formal_start_telemetry';$payload=Gzip64([IO.File]::ReadAllBytes([string]$binding.r1hReader.path));$template='sudo -S -k -p '''' /usr/bin/bash -c ''set -eu; out="$1"; test ! -e "$out"; printf %s "$2" | /usr/bin/base64 -d | /usr/bin/gzip -dc | /usr/bin/python3 - --node /dev/xdma0_user --expect formal --twice --delay 1.0 --output-dir "$out"'' _ ''{0}'' ''{1}''';$remote=$template-f$remoteOut,$payload
&$script:R1hAcceptedTools.ContextualPlink.Path -PlinkPath $script:R1hAcceptedTools.Plink084.Path -HostKey 'SHA256:yunI1fwP5I6WfGcSVkyaPxd0siCbdSiOOXVrP0wtEu8' -RemoteCommand $remote -EvidencePath $out -ExpectedIp '10.132.1.111' -ExpectedUser 'vcdeagent1' -EvidenceKind R1H_EXISTING_FORMAL_TELEMETRY_READ_ONLY -SendPasswordToStdin -SudoPasswordCopies 1 -TimeoutSeconds 180
$rc=$LASTEXITCODE;$text=[IO.File]::ReadAllText($out);if($rc-ne0-or(Value $text RESULT)-cne'PASS'-or(Value $text EXIT_CODE)-cne'0'-or(Value $text READ_ONLY)-cne'YES'-or(Value $text STATIC_SNAPSHOTS_MATCH)-cne'YES'){throw 'existing exact-formal reader gate failed'};'EXISTING_FORMAL_TELEMETRY_GATE=PASS';"R1H_READER_SHA256=$([string]$binding.r1hReader.sha256)";"TELEMETRY_SHA256=$((Get-FileHash -Algorithm SHA256 -LiteralPath $out).Hash)"

