[CmdletBinding()]
param([Parameter(Mandatory)][string]$BindingPath)

$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
. 'C:\FPGA\V41_NVP_R1H_BRAM_BACKED_LARGE_SAMPLE\09_HOST_TOOLS\R1hCampaignCommon.ps1'
function Gzip64([byte[]]$b){$m=[IO.MemoryStream]::new();try{$g=[IO.Compression.GzipStream]::new($m,[IO.Compression.CompressionLevel]::Optimal,$true);try{$g.Write($b,0,$b.Length)}finally{$g.Dispose()};[Convert]::ToBase64String($m.ToArray())}finally{$m.Dispose()}}
function Value([string]$text,[string]$key){$m=[regex]::Matches($text,'(?m)^'+[regex]::Escape($key)+'=([^\r\n]*)\r?$');if($m.Count-ne1){throw "$key exact-line count is $($m.Count)"};$m[0].Groups[1].Value}
$binding=Get-R1hBindingDocument -BindingPath $BindingPath;Assert-R1hAcceptedToolSet
$baselinePath=Join-Path $script:R1hPrecheckRoot 'R1H_HOST_BASELINE_GATE.txt';$jtagPath=Join-Path $script:R1hPrecheckRoot 'R1H_START_JTAG_DONE_GATE.txt'
$baseline=[IO.File]::ReadAllText($baselinePath);$jtag=[IO.File]::ReadAllText($jtagPath);if((Value $baseline R1H_HOST_BASELINE)-cne'PASS_2_OF_2'-or(Value $jtag R1H_START_JTAG_GATE)-cne'PASS_5_OF_5'){throw 'fresh baseline/JTAG predecessor gate failed'};$bootId=Value $baseline R1H_BOOT_ID_BASELINE;$jtagDone=Value $jtag DONE
$output=Join-Path $script:R1hPrecheckRoot 'START_SAFETY_DISCOVERY.log';$gatePath=Join-Path $script:R1hPrecheckRoot 'R1H_START_SAFETY_GATE.txt';$adapterReceipt=Join-Path $script:R1hPrecheckRoot 'START_SAFETY_PAYLOAD_ADAPTER_RECEIPT.txt';foreach($p in @($output,$gatePath,$adapterReceipt)){if(Test-Path -LiteralPath $p){throw "refusing to overwrite start-safety evidence: $p"}}
$sourcePath=$script:R1hAcceptedTools.PreBootstrapSafetyPayload.Path;$source=[IO.File]::ReadAllText($sourcePath,[Text.UTF8Encoding]::new($false,$true));$startMarker='for evidence_dir in \';$start=$source.IndexOf($startMarker,[StringComparison]::Ordinal);$endMarker="`n`nmapfile -t xilinx_functions";$end=$source.IndexOf($endMarker,$start,[StringComparison]::Ordinal);if($start-lt0-or$end-lt0){throw 'accepted prebootstrap remote-directory block was not found exactly'};$oldBlock=$source.Substring($start,$end-$start);if([regex]::Matches($oldBlock,'/home/vcdeagent1/FPGA_AHD_HOST/v41_nvp_r1e_r7/').Count-ne3){throw 'accepted prebootstrap block no longer contains exactly three R7 directory literals'};$nl=if($source.Contains("`r`n",[StringComparison]::Ordinal)){"`r`n"}else{"`n"};$remoteDirs=@('bootstrap_driver','a1_driver','b1_driver','a2_driver','b2_driver','a3_driver','b3_driver')|ForEach-Object{"  /home/vcdeagent1/FPGA_AHD_HOST/v41_nvp_r1h/$_"};for($i=0;$i-lt$remoteDirs.Count-1;$i++){$remoteDirs[$i]+=' \'};$newBlock='for evidence_dir in \'+$nl+($remoteDirs-join$nl)+'; do'+$nl+'  [[ ! -e $evidence_dir ]] || fail DRIVER_EVIDENCE_DIRECTORY_NOT_FRESH 87'+$nl+'  printf ''FRESH_DRIVER_EVIDENCE_DIRECTORY=%s STATE=ABSENT_FRESH\n'' "$evidence_dir"'+$nl+'done';$adapted=$source.Substring(0,$start)+$newBlock+$source.Substring($end);if($adapted.Contains('/v41_nvp_r1e_r7/',[StringComparison]::Ordinal)-or[regex]::Matches($adapted,'/home/vcdeagent1/FPGA_AHD_HOST/v41_nvp_r1h/').Count-ne7){throw 'prebootstrap directory-block adapter failed closed'};$adaptedBytes=[Text.UTF8Encoding]::new($false).GetBytes($adapted);$adaptedSha=[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($adaptedBytes));if($adaptedSha-cne'FF5BD477DA58EA481CD6605A03C5FF4A7B1C4861CEEDA16AA96D78BF1FBBD378'){throw 'prebootstrap adapted-payload SHA-256 mismatch'};Write-R1hUtf8NoBom -Path $adapterReceipt -Lines @("BASE_PAYLOAD_SHA256=$($script:R1hAcceptedTools.PreBootstrapSafetyPayload.Sha256)",'ADAPTER_CLASS=REMOTE_EVIDENCE_DIRECTORY_BLOCK_ONLY','R7_DIRECTORY_COUNT_REMOVED=3','R1H_DIRECTORY_COUNT_ADDED=7',"ADAPTED_PAYLOAD_SHA256=$adaptedSha",'ADAPTED_PAYLOAD_SHA256_GATE=PASS');$payload=Gzip64($adaptedBytes);$bar=Gzip64([IO.File]::ReadAllBytes($script:R1hAcceptedTools.BarParser.Path));$template='sudo -S -k -p '''' /usr/bin/bash -c ''printf %s "$1" | /usr/bin/base64 -d | /usr/bin/gzip -dc | /usr/bin/bash -s -- "$2" "$3" "$4"'' _ ''{0}'' ''{1}'' ''{2}'' ''{3}''';$remote=$template-f$payload,$bootId,$bar,$script:R1hAcceptedTools.BarParser.Sha256
&$script:R1hAcceptedTools.ContextualPlink.Path -PlinkPath $script:R1hAcceptedTools.Plink084.Path -HostKey 'SHA256:yunI1fwP5I6WfGcSVkyaPxd0siCbdSiOOXVrP0wtEu8' -RemoteCommand $remote -EvidencePath $output -ExpectedIp '10.132.1.111' -ExpectedUser 'vcdeagent1' -EvidenceKind R1H_START_SAFETY_READ_ONLY -SendPasswordToStdin -SudoPasswordCopies 1 -TimeoutSeconds 180
$rc=$LASTEXITCODE;$text=[IO.File]::ReadAllText($output);$fail=[Collections.Generic.List[string]]::new();try{$result=Value $text RESULT;$exit=Value $text EXIT_CODE;$remoteGate=Value $text PRE_BOOTSTRAP_HOST_SAFETY_GATE;$endpointCount=Value $text EXPECTED_ENDPOINT_COUNT;$endpointState=Value $text PRE_BOOTSTRAP_ENDPOINT_STATE;$link=Value $text ENDPOINT_LINK;$bar0=Value $text BAR0_BYTES;$bar1=Value $text BAR1_BYTES;$driver=Value $text PRE_BOOTSTRAP_DRIVER_STATE;$module=Value $text XDMA_MODULE_PRESENT;$nodes=Value $text XDMA_NODE_COUNT;$owners=Value $text XDMA_NODE_OWNERS;$dma=Value $text TASK_DMA_COMMANDS;$health=Value $text KERNEL_AER_XDMA_HEALTH;$kernel=Value $text CURRENT_KERNEL;$nextKernel=Value $text NEXT_REBOOT_KERNEL_PROVEN}catch{$fail.Add($_.Exception.Message);$result='UNKNOWN';$exit='UNKNOWN';$remoteGate='UNKNOWN';$endpointCount='UNKNOWN';$endpointState='UNKNOWN';$link='UNKNOWN';$bar0='UNKNOWN';$bar1='UNKNOWN';$driver='UNKNOWN';$module='UNKNOWN';$nodes='UNKNOWN';$owners='UNKNOWN';$dma='UNKNOWN';$health='UNKNOWN';$kernel='UNKNOWN';$nextKernel='UNKNOWN'}
$safe=($rc-eq0-and$result-ceq'PASS'-and$exit-ceq'0'-and$remoteGate-ceq'PASS'-and$owners-ceq'0'-and$dma-ceq'0'-and$health-ceq'PASS'-and$kernel-ceq'7.0.0-29-generic'-and$nextKernel-ceq'7.0.0-29-generic');$existingCandidate=($safe-and$jtagDone-ceq'1'-and$endpointCount-ceq'1'-and$endpointState-ceq'PRESENT_EXACT'-and$link-ceq'GEN1_X1'-and$bar0-ceq'131072'-and$bar1-ceq'65536'-and$driver-ceq'EXACT_PINNED_PRESENT'-and$module-ceq'YES'-and$nodes-ceq'21');$gate=if($existingCandidate){'PASS_EXISTING_FORMAL_INFRA_CANDIDATE'}elseif($safe){'PASS_SAFE_BOOTSTRAP_REQUIRED'}else{'FAIL_UNSAFE'}
$lines=@("R1H_START_SAFETY_GATE=$gate","JTAG_DONE=$jtagDone","KERNEL=$kernel","NEXT_REBOOT_KERNEL=$nextKernel","ENDPOINT_COUNT=$endpointCount","ENDPOINT_STATE=$endpointState","LINK=$link","BAR0_BYTES=$bar0","BAR1_BYTES=$bar1","PINNED_DRIVER=$driver","XDMA_MODULE_PRESENT=$module","XDMA_NODE_COUNT=$nodes","NODE_OWNERS=$owners","TASK_DMA=$dma","KERNEL_AER_HEALTH=$health","BASE_SAFETY_PAYLOAD_SHA256=$($script:R1hAcceptedTools.PreBootstrapSafetyPayload.Sha256)","ADAPTED_SAFETY_PAYLOAD_SHA256=$adaptedSha","PAYLOAD_ADAPTER_RECEIPT_SHA256=$((Get-FileHash -Algorithm SHA256 -LiteralPath $adapterReceipt).Hash)","DISCOVERY_SHA256=$((Get-FileHash -Algorithm SHA256 -LiteralPath $output).Hash)",'READ_ONLY_GATE=YES');Write-R1hUtf8NoBom -Path $gatePath -Lines $lines;$lines;if($gate-ceq'FAIL_UNSAFE'){exit 1}
