set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property PACKAGE_PIN E16 [get_ports vclk1]
set_property PACKAGE_PIN B16 [get_ports {vdo1[0]}]
set_property PACKAGE_PIN C16 [get_ports {vdo1[1]}]
set_property PACKAGE_PIN A17 [get_ports {vdo1[2]}]
set_property PACKAGE_PIN B17 [get_ports {vdo1[3]}]
set_property PACKAGE_PIN C17 [get_ports {vdo1[4]}]
set_property PACKAGE_PIN C18 [get_ports {vdo1[5]}]
set_property PACKAGE_PIN E17 [get_ports {vdo1[6]}]
set_property PACKAGE_PIN D18 [get_ports {vdo1[7]}]

set_property PACKAGE_PIN R16 [get_ports vclk2]
set_property PACKAGE_PIN R18 [get_ports {vdo2[0]}]
set_property PACKAGE_PIN T15 [get_ports {vdo2[1]}]
set_property PACKAGE_PIN T18 [get_ports {vdo2[2]}]
set_property PACKAGE_PIN T17 [get_ports {vdo2[3]}]
set_property PACKAGE_PIN U17 [get_ports {vdo2[4]}]
set_property PACKAGE_PIN V17 [get_ports {vdo2[5]}]
set_property PACKAGE_PIN U16 [get_ports {vdo2[6]}]
set_property PACKAGE_PIN V16 [get_ports {vdo2[7]}]

set_property PACKAGE_PIN K17 [get_ports nvp_irq]
set_property PACKAGE_PIN L18 [get_ports nvp_rst]
set_property PACKAGE_PIN M17 [get_ports nvp_sda]
set_property PACKAGE_PIN N17 [get_ports nvp_scl]
set_property PACKAGE_PIN C13 [get_ports ref27]

set_property IOSTANDARD LVCMOS33 [get_ports {vclk1 vdo1[*] vclk2 vdo2[*] nvp_irq nvp_rst nvp_sda nvp_scl ref27}]
set_property SLEW SLOW [get_ports {nvp_rst nvp_sda nvp_scl}]
set_property DRIVE 8 [get_ports {nvp_rst nvp_sda nvp_scl}]

create_clock -name vclk1_148m5 -period 6.734 [get_ports vclk1]
create_clock -name vclk2_148m5 -period 6.734 [get_ports vclk2]
create_clock -name ref27_27m -period 37.037 [get_ports ref27]
