`ifndef R1H_PROBE_COMMON_OUTPUTS_GENERATED_SVH
`define R1H_PROBE_COMMON_OUTPUTS_GENERATED_SVH
`define PROBE_COMMON_OUTPUTS \
  `PROBE_X(3, attempt_limit_status) \
  `PROBE_X(32, block_read_nack_count) \
  `PROBE_X(2, current_scheduler_phase) \
  `PROBE_X(32, data_adjacent_nack_pairs) \
  `PROBE_X(16, data_first_nack_index) \
  `PROBE_X(16, data_last_nack_index) \
  `PROBE_X(32, data_max_consecutive_nacks) \
  `PROBE_X(1, data_nack_index_overflow) \
  `PROBE_X(16, data_nack_index_stored_count) \
  `PROBE_X(32, data_prereq_regaddr_acks) \
  `PROBE_X(32, data_prereq_regaddr_nacks) \
  `PROBE_X(32, data_prereq_regaddr_opportunities) \
  `PROBE_X(32, data_prereq_waddr_acks) \
  `PROBE_X(32, data_prereq_waddr_nacks) \
  `PROBE_X(32, data_prereq_waddr_opportunities) \
  `PROBE_X(32, data_run_count) \
  `PROBE_X(32, data_target_acks) \
  `PROBE_X(32, data_target_nacks) \
  `PROBE_X(32, data_target_opportunities) \
  `PROBE_X(32, data_timeouts) \
  `PROBE_X(32, data_transaction_attempts) \
  `PROBE_X(8, entry_bank) \
  `PROBE_X(1, entry_bank_valid) \
  `PROBE_X(1, final_bus_idle) \
  `PROBE_X(1, legacy_bus_idle_qualified) \
  `PROBE_X(1, legacy_bus_idle_timeout) \
  `PROBE_X(1, legacy_guard_complete) \
  `PROBE_X(1, legacy_init_done_seen) \
  `PROBE_X(1, legacy_scl_timeout) \
  `PROBE_X(1, original_bank_restore_verified) \
  `PROBE_X(1, original_bank_restored) \
  `PROBE_X(8, probe_abort_code) \
  `PROBE_X(1, probe_aborted) \
  `PROBE_X(1, probe_active) \
  `PROBE_X(1, probe_done) \
  `PROBE_X(48, probe_done_freerun) \
  `PROBE_X(8, probe_restore_failure_code) \
  `PROBE_X(1, probe_scl_release) \
  `PROBE_X(1, probe_sda_release) \
  `PROBE_X(48, probe_start_freerun) \
  `PROBE_X(32, probe_status) \
  `PROBE_X(1, probe_terminal) \
  `PROBE_X(32, probe_timeout_count_total) \
  `PROBE_X(32, regaddr_adjacent_nack_pairs) \
  `PROBE_X(16, regaddr_first_nack_index) \
  `PROBE_X(16, regaddr_last_nack_index) \
  `PROBE_X(32, regaddr_max_consecutive_nacks) \
  `PROBE_X(1, regaddr_nack_index_overflow) \
  `PROBE_X(16, regaddr_nack_index_stored_count) \
  `PROBE_X(32, regaddr_prereq_waddr_acks) \
  `PROBE_X(32, regaddr_prereq_waddr_nacks) \
  `PROBE_X(32, regaddr_prereq_waddr_opportunities) \
  `PROBE_X(32, regaddr_run_count) \
  `PROBE_X(32, regaddr_target_acks) \
  `PROBE_X(32, regaddr_target_nacks) \
  `PROBE_X(32, regaddr_target_opportunities) \
  `PROBE_X(32, regaddr_timeouts) \
  `PROBE_X(32, regaddr_transaction_attempts) \
  `PROBE_X(8, restored_bank_readback) \
  `PROBE_X(1, restored_bank_readback_valid) \
  `PROBE_X(32, round_robin_scheduler_rounds) \
  `PROBE_X(8, safe_bank_readback) \
  `PROBE_X(1, safe_bank_readback_valid) \
  `PROBE_X(1, safe_bank_select_write_ok) \
  `PROBE_X(1, safe_bank_verify_ok) \
  `PROBE_X(1, safe_target_post_ok) \
  `PROBE_X(1, safe_target_post_valid) \
  `PROBE_X(8, safe_target_post_value) \
  `PROBE_X(1, safe_target_pre_ok) \
  `PROBE_X(1, safe_target_pre_valid) \
  `PROBE_X(8, safe_target_pre_value) \
  `PROBE_X(32, waddr_adjacent_nack_pairs) \
  `PROBE_X(16, waddr_first_nack_index) \
  `PROBE_X(16, waddr_last_nack_index) \
  `PROBE_X(32, waddr_max_consecutive_nacks) \
  `PROBE_X(1, waddr_nack_index_overflow) \
  `PROBE_X(16, waddr_nack_index_stored_count) \
  `PROBE_X(32, waddr_run_count) \
  `PROBE_X(32, waddr_target_acks) \
  `PROBE_X(32, waddr_target_nacks) \
  `PROBE_X(32, waddr_target_opportunities) \
  `PROBE_X(32, waddr_timeouts) \
  `PROBE_X(32, waddr_transaction_attempts)
`endif
