
####################################################################################
# Generated by Vivado 2025.2 built on 'Fri Nov 14 19:35:11 GMT 2025' by 'xbuild'
# Command Used: write_xdc -exclude_physical -force C:/FPGA/G2B_LUT1_PRODUCT_PRECOMMIT_EVIDENCE_20260831_12/BUS_SKEW_GROUPS/ROUTED_TIMING_FULL_SEMANTIC_PASS_2.xdc
####################################################################################


####################################################################################
# Constraints from file : 'ROUTED_TIMING_FULL_SEMANTIC_PASS_1.xdc'
####################################################################################

create_clock -period 10.000 -name pcie_refclk_100 [get_ports sys_clk_p]
set_false_path -from [get_ports sys_rst_n]
current_instance XDMA/inst/xdma_v41_m1_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst
create_clock -period 10.000 -name txoutclk_x0y0 [get_pins {inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtp_channel.gtpe2_channel_i/TXOUTCLK}]
set_false_path -to [get_pins inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/S0]
set_false_path -to [get_pins inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/S1]
current_instance -quiet
create_generated_clock -name clk_125mhz_x0y0 [get_pins XDMA/inst/xdma_v41_m1_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT0]
create_generated_clock -name clk_250mhz_x0y0 [get_pins XDMA/inst/xdma_v41_m1_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/mmcm_i/CLKOUT1]
current_instance XDMA/inst/xdma_v41_m1_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst
create_generated_clock -name clk_125mhz_mux_x0y0 -source [get_pins inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/I0] -divide_by 1 [get_pins inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/O]
create_generated_clock -name clk_250mhz_mux_x0y0 -source [get_pins inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/I1] -divide_by 1 -add -master_clock [get_clocks -of [get_pins inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/I1]] [get_pins inst/gt_top_i/pipe_wrapper_i/pipe_clock_int.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/O]
set_clock_groups -name pcieclkmux -physically_exclusive -group clk_125mhz_mux_x0y0 -group clk_250mhz_mux_x0y0
set_false_path -through [get_pins -filter REF_PIN_NAME=~PLPHYLNKUPN -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ * }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~PLRECEIVEDHOTRST -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ * }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~RXELECIDLE -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ IO.gt.* }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~TXPHINITDONE -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ IO.gt.* }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~TXPHALIGNDONE -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ IO.gt.* }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~TXDLYSRESETDONE -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ IO.gt.* }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~RXDLYSRESETDONE -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ IO.gt.* }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~RXPHALIGNDONE -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ IO.gt.* }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~RXCDRLOCK -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ IO.gt.* }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~CFGMSGRECEIVEDPMETO -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ * }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~PLL0LOCK -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ IO.gt.* }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~RXPMARESETDONE -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ IO.gt.* }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~RXSYNCDONE -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ IO.gt.* }]]
set_false_path -through [get_pins -filter REF_PIN_NAME=~TXSYNCDONE -of_objects [get_cells -hierarchical -filter { PRIMITIVE_TYPE =~ IO.gt.* }]]
current_instance -quiet
create_clock -period 6.734 -name nvp_vclk1 [get_ports vclk1]
set_input_delay -clock nvp_vclk1 -max 6.313 [get_ports {vdo1_data[*]}]
set_input_delay -clock nvp_vclk1 -min 2.104 [get_ports {vdo1_data[*]}]
set_false_path -from [get_ports {vdo1_data[*]}] -fall_to [get_clocks nvp_vclk1]
set_false_path -from [get_ports sys_rst_n]
set_max_delay -datapath_only -from [get_cells -quiet -hier -regexp {.*MAILBOX/cfg_hold_pcie_reg\[[0-9]+\]}] -to [get_cells -quiet -hier -regexp {.*MAILBOX/nvp_cfg_(abort|arm|capture_generation|clear_errors|line_count_requested|single_line|target_line|window_16_lines)_reg(\[[0-9]+\])?}] 6.000
set_bus_skew -from [get_cells -quiet -hier -regexp {.*MAILBOX/cfg_hold_pcie_reg\[[0-9]+\]}] -to [get_cells -quiet -hier -regexp {.*MAILBOX/nvp_cfg_(abort|arm|capture_generation|clear_errors|line_count_requested|single_line|target_line|window_16_lines)_reg(\[[0-9]+\])?}] 3.000
set _xlnx_shared_i0 [get_cells -quiet -hier -regexp {.*MAILBOX/status_hold_nvp_reg\[[0-9]+\]}]
set _xlnx_shared_i1 [get_cells -quiet -hier -regexp {.*MAILBOX/status_bus_pcie_reg\[[0-9]+\]}]
set_max_delay -datapath_only -from $_xlnx_shared_i0 -to $_xlnx_shared_i1 6.000
set_bus_skew -from $_xlnx_shared_i0 -to $_xlnx_shared_i1 3.000
set_false_path -to [get_pins -quiet -of_objects [get_cells -quiet -hier -regexp {.*(MAILBOX/(cfg_req_sync1_nvp|cfg_ack_sync1_pcie|status_req_sync1_pcie|status_ack_sync1_nvp)_reg|BAR_TARGET/(release_sync1_reg|commit_sync1_reg)(\[[0-9]+\])?)}] -filter {REF_PIN_NAME == D}]
set_max_delay -datapath_only -from [get_cells -quiet -hier -regexp {.*(active_sav_gray_nvp_reg|slot_commit_gray_nvp_reg|vclk_edge_gray_nvp_reg)\[[0-9]+\]}] -to [get_pins -quiet -of_objects [get_cells -quiet -hier -regexp {.*(active_sav_gray_sync1_pcie_reg|slot_commit_gray_sync1_pcie_reg|vclk_edge_gray_sync1_user_reg)\[[0-9]+\]}] -filter {REF_PIN_NAME == D}] 6.000
set_bus_skew -from [get_cells -quiet -hier -regexp {.*(active_sav_gray_nvp_reg|slot_commit_gray_nvp_reg|vclk_edge_gray_nvp_reg)\[[0-9]+\]}] -to [get_pins -quiet -of_objects [get_cells -quiet -hier -regexp {.*(active_sav_gray_sync1_pcie_reg|slot_commit_gray_sync1_pcie_reg|vclk_edge_gray_sync1_user_reg)\[[0-9]+\]}] -filter {REF_PIN_NAME == D}] 3.000
set_false_path -to [get_pins -quiet -hier -regexp {.*(NVP_PHYSICAL_FRONTEND/ingress_reset_sync_reg\[[0-9]+\]/PRE|nvp_ready_sync_reg\[[0-9]+\]/CLR)}]
current_instance CAPTURE_SUBSYSTEM/PCIE_RESET_TO_PCIE_SYNC
set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]
current_instance -quiet
current_instance CAPTURE_SUBSYSTEM/NVP_RESET_TO_NVP_SYNC
set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]
current_instance -quiet
current_instance CAPTURE_SUBSYSTEM/PCIE_RESET_TO_NVP_SYNC
set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]
current_instance -quiet
current_instance XDMA/inst/xdma_v41_m1_pcie2_to_pcie3_wrapper_i/xdma_v41_m1_axi_stream_intf_i/xdma_v41_m1_rx_demux_i/tgt_brdg_fifo_inst/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.gnsckt_wrst.rst_wr_reg2_inst
set_false_path -through [get_ports -scoped_to_current_instance -no_traverse src_arst]
current_instance -quiet
current_instance XDMA/inst/udma_wrapper/dma_top/base/IRQ_INST/usr_irq_xpm_cdc
set_false_path -to [get_cells {syncstages_ff_reg[0]}]
current_instance -quiet
current_instance XDMA/inst/xdma_v41_m1_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/pl_received_hot_rst_cdc
set_false_path -to [get_cells {syncstages_ff_reg[0]}]
current_instance -quiet
current_instance XDMA/inst/xdma_v41_m1_pcie2_to_pcie3_wrapper_i/pcie2_ip_i/inst/inst/phy_lnk_up_cdc
set_false_path -to [get_cells {syncstages_ff_reg[0]}]
current_instance -quiet
current_instance XDMA/inst/xdma_v41_m1_pcie2_to_pcie3_wrapper_i/xdma_v41_m1_axi_stream_intf_i/xdma_v41_m1_rx_demux_i/dma_cpl_fifo_inst/U0/inst_fifo_gen/gaxis_fifo.gaxisf.axisf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.gsckt_wrst.xpm_cdc_sync_rst_inst_wrst
set_false_path -to [get_cells {syncstages_ff_reg[0]}]

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
