[CmdletBinding()]
param([ValidateRange(60,900)][int]$TimeoutSeconds=600)

$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
. (Join-Path $PSScriptRoot 'R1hCampaignCommon.ps1')
function Cmd([string]$v){if($v-notmatch'^[A-Za-z0-9_:\\\./-]+$'){throw "unsafe cmd token: $v"};$v}
function Value([string]$text,[string]$key){$m=[regex]::Matches($text,'(?m)^'+[regex]::Escape($key)+'=([^\r\n]*)\r?$');if($m.Count-lt1){throw "$key exact-line count is 0"};$values=@($m|ForEach-Object{$_.Groups[1].Value}|Select-Object -Unique);if($values.Count-ne1){throw "$key has conflicting repeated values"};$values[0]}
$safetyRoot=Join-Path $script:R1hPrecheckRoot '00_MINIMAL_SAFETY';Assert-R1hAcceptedToolSet
$raw=Join-Path $safetyRoot 'START_JTAG_RECONFIRMATION_RAW.log';$log=Join-Path $safetyRoot 'START_JTAG_RECONFIRMATION_VIVADO.log';$jou=Join-Path $safetyRoot 'START_JTAG_RECONFIRMATION_VIVADO.jou';$csv=Join-Path $safetyRoot 'START_JTAG_RECONFIRMATION_MATRIX.csv';$targetProps=Join-Path $safetyRoot 'START_JTAG_TARGET_PROPERTIES.tsv';$deviceProps=Join-Path $safetyRoot 'START_JTAG_DEVICE_PROPERTIES.tsv';$gatePath=Join-Path $safetyRoot 'R1H_R4_JTAG_SAFETY_GATE.txt'
foreach($p in @($raw,$log,$jou,$csv,$targetProps,$deviceProps,$gatePath)){if(Test-Path -LiteralPath $p){throw "refusing to overwrite JTAG precheck evidence: $p"}}
$tcl=$script:R1hAcceptedTools.JtagReconfirmationTcl.Path;$text=[IO.File]::ReadAllText($tcl)
if([regex]::IsMatch($text,'(?m)^\s*program_hw_devices\b')-or[regex]::IsMatch($text,'(?m)^\s*set_property\b')){throw 'read-only Tcl static audit failed'}
$command=@('call',(Cmd $script:R1hAcceptedTools.VivadoSettings.Path),'&&',(Cmd $script:R1hAcceptedTools.VivadoLauncher.Path),'-mode','batch','-notrace','-log',(Cmd $log),'-journal',(Cmd $jou),'-source',(Cmd $tcl),'-tclargs',(Cmd $csv),(Cmd $targetProps),(Cmd $deviceProps))-join' '
$psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName="$env:SystemRoot\System32\cmd.exe";$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.WorkingDirectory=$safetyRoot;$psi.Arguments='/d /s /c "'+$command+'"'
$p=[Diagnostics.Process]::new();$p.StartInfo=$psi;$timeout=$false;$start=[Diagnostics.Stopwatch]::GetTimestamp();try{if(-not$p.Start()){throw'Vivado start failed'};$outTask=$p.StandardOutput.ReadToEndAsync();$errTask=$p.StandardError.ReadToEndAsync();if(-not$p.WaitForExit($TimeoutSeconds*1000)){$timeout=$true;$p.Kill($true);$p.WaitForExit()};$out=$outTask.GetAwaiter().GetResult();$err=$errTask.GetAwaiter().GetResult();$rc=$p.ExitCode}finally{$end=[Diagnostics.Stopwatch]::GetTimestamp();$p.Dispose()}
Write-R1hUtf8NoBom -Path $raw -Lines @("PROCESS_EXIT_CODE=$rc","TIMED_OUT=$(if($timeout){'YES'}else{'NO'})","START_TICKS=$start","END_TICKS=$end","READ_ONLY_JTAG_TCL_SHA256=$($script:R1hAcceptedTools.JtagReconfirmationTcl.Sha256)",'STDOUT_BEGIN',$out.TrimEnd(),'STDOUT_END','STDERR_BEGIN',$err.TrimEnd(),'STDERR_END')
$combined=$out+"`n"+$err;$fail=[Collections.Generic.List[string]]::new()
try{$canonical=Value $combined R7_SELECTED_JTAG_CANONICAL_ID;$target=Value $combined R7_FULL_JTAG_TARGET_PATH;$samples=Value $combined R7_JTAG_RECONFIRMATION_SAMPLES;$sessionGate=Value $combined R7_JTAG_RECONFIRMATION_SESSION_GATE;$programs=Value $combined FPGA_PROGRAM_INVOCATIONS_THIS_SESSION;$freq=Value $combined JTAG_FREQUENCY_CHANGED}catch{$fail.Add($_.Exception.Message);$canonical='UNKNOWN';$target='UNKNOWN';$samples='UNKNOWN';$sessionGate='UNKNOWN';$programs='UNKNOWN';$freq='UNKNOWN'}
$rows=if(Test-Path -LiteralPath $csv){@(Import-Csv -LiteralPath $csv)}else{@()};$doneValues=@($rows|ForEach-Object done|Select-Object -Unique);$partValues=@($rows|ForEach-Object part|Select-Object -Unique);$idValues=@($rows|ForEach-Object idcode|Select-Object -Unique);$targetValues=@($rows|ForEach-Object target_path|Select-Object -Unique);$countPass=($rows.Count-eq5-and@($rows|Where-Object{[string]$_.target_count-cne'1'-or[string]$_.device_count-cne'1'-or[string]$_.refresh_result-cne'PASS'}).Count-eq0)
if($timeout-or$rc-ne0-or$canonical-cne$script:R1hCanonicalTarget-or[string]::IsNullOrWhiteSpace($target)-or(-not$target.EndsWith($script:R1hCanonicalSuffix,[StringComparison]::Ordinal)-and$target-cne$script:R1hCanonicalTarget)-or$samples-cne'5'-or$sessionGate-cne'PASS'-or$programs-cne'0'-or$freq-cne'NO'-or-not$countPass-or$doneValues.Count-ne1-or$doneValues[0]-cnotin@('0','1')-or$partValues.Count-ne1-or$partValues[0]-cne$script:R1hExpectedPart-or$idValues.Count-ne1-or$idValues[0]-cne$script:R1hExpectedIdcode-or$targetValues.Count-ne1-or$targetValues[0]-cne$target){$fail.Add('EXACT_SELECTED_JTAG_STABILITY_GATE')}
$gate=if($fail.Count-eq0){'PASS'}else{'FAIL'};$done=if($doneValues.Count-eq1){$doneValues[0]}else{'UNKNOWN'};$lines=[Collections.Generic.List[string]]::new();foreach($line in @("R1H_R4_JTAG_SAFETY_GATE=$gate","SELECTED_JTAG=$canonical","R1H_FULL_JTAG_TARGET_PATH=$target","FPGA_PART=$(if($partValues.Count-eq1){$partValues[0]}else{'UNKNOWN'})","FPGA_IDCODE=$(if($idValues.Count-eq1){$idValues[0]}else{'UNKNOWN'})","CURRENT_DONE_INFORMATIONAL=$done",'JTAG_STABILITY_SAMPLES=5',"FPGA_PROGRAM_INVOCATIONS_THIS_SCRIPT=$programs","JTAG_FREQUENCY_CHANGED=$freq","READ_ONLY_GATE=$(if($gate-eq'PASS'){'YES'}else{'NOT_PROVEN'})","RAW_SHA256=$((Get-FileHash -Algorithm SHA256 -LiteralPath $raw).Hash)","MATRIX_SHA256=$((Get-FileHash -Algorithm SHA256 -LiteralPath $csv).Hash)")){$lines.Add($line)};foreach($f in $fail){$lines.Add("FAILURE=$f")};Write-R1hUtf8NoBom -Path $gatePath -Lines $lines.ToArray();$lines;if($gate-eq'FAIL'){exit 1}
