[CmdletBinding()]
param()
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
[Globalization.CultureInfo]::CurrentCulture=[Globalization.CultureInfo]::InvariantCulture
. (Join-Path $PSScriptRoot 'R1hCampaignCommon.ps1')
function Kv([string]$p){$m=@{};foreach($l in [IO.File]::ReadAllLines($p)){if($l-match'^([A-Z0-9_]+)=(.*)$'){if($m.ContainsKey($Matches[1])){throw"duplicate $($Matches[1]) in $p"};$m[$Matches[1]]=$Matches[2]}};$m}
function Need($m,[string]$k,[string]$v,[string]$p){$a=if($m.ContainsKey($k)){$m[$k]}else{'<MISSING>'};if([string]$a-cne$v){throw"$k mismatch in ${p}: $a != $v"}}
function LogValue([string]$t,[string]$k){$m=[regex]::Matches($t,'(?m)^'+[regex]::Escape($k)+'=([^\r\n]*)\r?$');if($m.Count-ne1){throw"$k count $($m.Count)"};$m[0].Groups[1].Value}
$bindingPath=Join-Path $script:R1hPrecheckRoot 'R1H_R4_HARDWARE_BINDING.json';$binding=Get-R1hBindingDocument $bindingPath;Assert-R1hAcceptedToolSet
$phase=Get-R1hPhaseSpec B1;$d=Assert-R1hPhaseDirectory $phase
$reservationPath=Join-Path $d 'PROGRAM_ATTEMPT_RESERVATION.txt';$logPath=Join-Path $d 'PROGRAM_VIVADO.log';$journalPath=Join-Path $d 'PROGRAM_VIVADO.jou';$supervisorPath=Join-Path $d 'PROGRAM_SUPERVISOR.log';$timingPath=Join-Path $d 'PROGRAM_TIMING_RECEIPT.txt';$recoveryPath=Join-Path $d 'PROGRAM_POSTPROCESS_RECOVERY_RECEIPT.txt'
foreach($p in @($timingPath,$recoveryPath)){if(Test-Path -LiteralPath $p){throw"refusing to overwrite B1 recovery output: $p"}}
foreach($p in @($reservationPath,$logPath,$journalPath,$supervisorPath,$bindingPath)){if(-not(Test-Path -LiteralPath $p -PathType Leaf)){throw"missing B1 input: $p"}}
$r=Kv $reservationPath;$bitPath=[string]$binding.formalBit.path;$bitSha=(Get-FileHash -LiteralPath $bitPath -Algorithm SHA256).Hash;$predPath='C:\FPGA\V41_NVP_R1H_R4_SUPER_FAST\hardware\02_A1\VALID_ARM_A_RECEIPT.txt';$predSha=(Get-FileHash -LiteralPath $predPath -Algorithm SHA256).Hash
foreach($x in @(@('PHASE_TOKEN','B1'),@('PROGRAM_ROLE','ARM_B_FORMAL'),@('OBSERVER_MODE','TRANSITION_FROM_PROVEN_CONFIGURED_IMAGE'),@('GLOBAL_RETRY_ATTEMPT','NO'),@('PROGRAM_INVOCATION_GLOBAL_MAX','8'),@('BIT_PATH',$bitPath),@('BIT_SHA256',[string]$binding.formalBit.sha256),@('CONFIGURED_RECEIPT_PATH',$predPath),@('CONFIGURED_RECEIPT_SHA256',$predSha),@('RESERVATION_IMMUTABLE','YES'))){Need $r $x[0] $x[1] $reservationPath}
if($bitSha-cne'7E4E909D78C2BE5C1E0ECA56229F2B88ECC2DBF5974B32BDF07EF1AFCD9449A2'){throw'formal bit mismatch'}
$pred=Kv $predPath;foreach($x in @(@('RECEIPT_TYPE','VALID_ARM_A_RECEIPT'),@('RECEIPT_STATUS','PASS'),@('PHASE_TOKEN','A1'),@('R1H_FULL_JTAG_TARGET_PATH',[string]$binding.selectedFullJtagTargetPath),@('FPGA_DONE','1'),@('R1H_BIT_SHA256','73E973A42083D7D22CF427ED09B73F8DE2D2C05506697EA36E1FA1B5F7163C41'),@('ARM_A_SAMPLE_VALID','YES'),@('ARM_A_TERMINAL_SAFE_DONE1','YES'))){Need $pred $x[0] $x[1] $predPath}
$log=[IO.File]::ReadAllText($logPath);if([regex]::Matches($log,'(?m)^ERROR:').Count-ne0-or[regex]::Matches($log,'(?m)^program_hw_devices:').Count-ne1-or[regex]::Matches($log,'(?m)^INFO: \[Common 17-206\] Exiting Vivado at ').Count-ne1){throw'B1 terminal log gate failed'}
foreach($x in @(@('PROGRAM_ROLE','ARM_B_FORMAL'),@('OBSERVER_MODE','TRANSITION_FROM_PROVEN_CONFIGURED_IMAGE'),@('PROVEN_CONFIGURED_IMAGE_RECEIPT','VALID_ARM_A_RECEIPT'),@('R6_SELECTED_JTAG_CANONICAL_ID','Xilinx/80802026a98b01'),@('R7_FULL_JTAG_TARGET_PATH',[string]$binding.selectedFullJtagTargetPath),@('PREPROGRAM_DONE_SAMPLE_COUNT','5'),@('PREPROGRAM_DONE_SAMPLES','1,1,1,1,1'),@('PREPROGRAM_DONE_READABLE','YES_5_OF_5'),@('PREPROGRAM_DONE_STABLE','YES'),@('TARGET_PART_IDCODE_STABLE','YES'),@('PREPROGRAM_DONE_VALUE','1'),@('PROGRAM_PRECONDITION','PASS'),@('PROGRAM_INVOCATION_CONSUMED','1'),@('PROGRAM_DONE','1'),@('FRESH_DONE_OBSERVATION','1'),@('PROGRAM_INVOCATIONS','1'),@('PROGRAM_TCL_RESULT','PASS_DONE_1'))){if((LogValue $log $x[0])-cne$x[1]){throw"B1 log mismatch $($x[0])"}}
$records=[Collections.Generic.List[object]]::new();foreach($line in [IO.File]::ReadAllLines($supervisorPath)){if($line-match'^SEQ=(\d+) TICK=(\d+) STREAM=([^ ]+) LINE=(.*)$'){$records.Add([pscustomobject]@{Sequence=[long]$Matches[1];Tick=[long]$Matches[2];Stream=$Matches[3];Line=$Matches[4];Raw=$Matches[4]})}}
. $script:R1hAcceptedTools.ProgramObserverParser.Path;$result=Test-I25ProgramObserver $records.ToArray()
if($result.CLASSIFICATION-cne'PASS_STARTUP_HIGH_DONE_1'-or$result.PROGRAM_INVOCATION_CONSUMED_COUNT-ne1-or$result.COUNT_GATE-cne'PASS'-or$result.ORDER_GATE-cne'PASS'-or$result.VENDOR_STARTUP_HIGH_COUNT-ne1-or$result.PROCESS_EXIT_ZERO_COUNT-ne1-or$result.TIMED_OUT_NO_COUNT-ne1){throw'accepted parser rejected B1 supervisor'}
$anchor=[Diagnostics.Stopwatch]::GetTimestamp();$freq=[Diagnostics.Stopwatch]::Frequency;$reservationSha=(Get-FileHash $reservationPath -Algorithm SHA256).Hash;$logSha=(Get-FileHash $logPath -Algorithm SHA256).Hash;$journalSha=(Get-FileHash $journalPath -Algorithm SHA256).Hash;$supervisorSha=(Get-FileHash $supervisorPath -Algorithm SHA256).Hash;$bindingSha=(Get-FileHash $bindingPath -Algorithm SHA256).Hash;$scriptSha=(Get-FileHash $PSCommandPath -Algorithm SHA256).Hash
$startText=LogValue $log PROGRAM_START_UTC;$returnText=LogValue $log I25_PROGRAM_RETURN_MARKER;$freshText=LogValue $log I25_FRESH_DONE_MARKER;$endText=LogValue $log PROGRAM_END_UTC
Write-R1hUtf8NoBom $recoveryPath @('PHASE_TOKEN=B1','RECOVERY_CLASS=POSTPROCESS_ONLY_AFTER_SUPERVISOR_APPEND_OVERLOAD_FAILURE','ORIGINAL_WRAPPER_RESULT=FAIL_TASK_LOCAL_APPENDALLLINES_ENCODING_OVERLOAD','ORIGINAL_WRAPPER_EXCEPTION=Cannot find an overload for AppendAllLines and the argument count 3.','VIVADO_CHILD_TERMINAL_RESULT=PASS_DONE_1','VIVADO_CHILD_NORMAL_EXIT=YES','PROGRAM_INVOCATIONS=1','PROGRAM_RETRIES=0','SECOND_PROGRAM_SESSION_RUN=NO','REBOOT_AFTER_WRAPPER_FAILURE=NO','TELEMETRY_AFTER_WRAPPER_FAILURE=NO',"PROGRAM_ATTEMPT_RESERVATION_SHA256=$reservationSha","PROGRAM_VIVADO_LOG_SHA256=$logSha","PROGRAM_VIVADO_JOURNAL_SHA256=$journalSha","PROGRAM_SUPERVISOR_LOG_SHA256=$supervisorSha","HARDWARE_BINDING_SHA256=$bindingSha","CONFIGURED_RECEIPT_SHA256=$predSha","FORMAL_BIT_SHA256=$bitSha","PROGRAM_TCL_SHA256=$($script:R1hAcceptedTools.ModeAwareObserverTcl.Sha256)","OBSERVER_PARSER_SHA256=$($script:R1hAcceptedTools.ProgramObserverParser.Sha256)","ORIGINAL_PROGRAM_RETURN_MARKER_TICKS=$($result.PROGRAM_RETURN_MARKER_TICKS)","ORIGINAL_FRESH_DONE_MARKER_TICKS=$($result.FRESH_DONE_MARKER_TICKS)","ORIGINAL_PROGRAM_START_UTC=$startText","ORIGINAL_PROGRAM_RETURN_UTC=$returnText","ORIGINAL_FRESH_DONE_UTC=$freshText","ORIGINAL_PROGRAM_END_UTC=$endText","STOPWATCH_FREQUENCY=$freq","CONSERVATIVE_RECOVERY_REFERENCE_TICKS=$anchor",'CONSERVATIVE_REFERENCE_AFTER_SUPERVISOR_AND_TERMINAL_LOG_VALIDATION=YES',"RECOVERY_SCRIPT_SHA256=$scriptSha",'RECOVERY_GATE=PASS_NO_HARDWARE_ACCESS')
$recoverySha=(Get-FileHash $recoveryPath -Algorithm SHA256).Hash
Write-R1hUtf8NoBom $timingPath @('PHASE_TOKEN=B1','PROGRAM_ROLE=ARM_B_FORMAL','OBSERVER_MODE=TRANSITION_FROM_PROVEN_CONFIGURED_IMAGE','PROVEN_CONFIGURED_IMAGE_RECEIPT=VALID_ARM_A_RECEIPT',"CONFIGURED_RECEIPT_SHA256=$predSha","R1H_FULL_JTAG_TARGET_PATH=$([string]$binding.selectedFullJtagTargetPath)","BIT_SHA256=$bitSha","PROGRAM_TCL_SHA256=$($script:R1hAcceptedTools.ModeAwareObserverTcl.Sha256)","OBSERVER_PARSER_SHA256=$($script:R1hAcceptedTools.ProgramObserverParser.Sha256)","TARGET_SELECTOR_SHA256=$($script:R1hAcceptedTools.SelectedTargetSelector.Sha256)","PROGRAM_SUPERVISOR_LOG_SHA256=$supervisorSha","PROGRAM_POSTPROCESS_RECOVERY_RECEIPT_SHA256=$recoverySha",'PROGRAM_RESULT=PASS_STARTUP_HIGH_DONE_1','PROGRAM_INVOCATIONS=1','PROGRAM_RETRIES=0','MODE_AWARE_PREPROGRAM_GATE=PASS','PREPROGRAM_DONE_SAMPLES=1,1,1,1,1','PREPROGRAM_DONE_VALUE=1','PROGRAM_INVOCATION_CONSUMED_MARKER_COUNT=1',"STOPWATCH_FREQUENCY=$freq","PROGRAM_RETURN_MARKER_TICKS=$anchor","FRESH_DONE_MARKER_TICKS=$anchor","WAIT_REFERENCE_TICKS=$anchor",'TIMING_REFERENCE_CLASS=CONSERVATIVE_POSTPROCESS_ANCHOR_AFTER_COMPLETED_PROGRAM','REQUIRED_MINIMUM_WAIT_SECONDS=5.000000000',"ORIGINAL_PROGRAM_RETURN_UTC=$returnText","ORIGINAL_FRESH_DONE_UTC=$freshText","TIMING_RECEIPT_CREATED_UTC=$([DateTime]::UtcNow.ToString('o'))",'TIMING_RECEIPT_STATUS=PASS_IMMUTABLE_WAIT_INPUT_RECOVERED_POSTPROCESS_ONLY')
"PROGRAM_TIMING_RECEIPT_SHA256=$((Get-FileHash $timingPath -Algorithm SHA256).Hash)";"PROGRAM_POSTPROCESS_RECOVERY_RECEIPT_SHA256=$recoverySha";"PROGRAM_SUPERVISOR_LOG_SHA256=$supervisorSha";'PROGRAM_SUPERVISOR_GATE=PASS_RECOVERED_POSTPROCESS_ONLY'
