"""Fixed ACQ1 MMIO contract; no generic NVP transaction interface exists."""

from __future__ import annotations

from scan1.mmio import MmioDevice


BASE = 0x12400
END = 0x127FF
MAGIC = BASE + 0x00
VERSION = BASE + 0x04
CAPABILITIES = BASE + 0x08
CONTROL = BASE + 0x0C
STATUS = BASE + 0x10
COMMAND_SEQUENCE = BASE + 0x14
COMPLETED_SEQUENCE = BASE + 0x18
LAST_OUTCOME = BASE + 0x1C
BASELINE_STATE = BASE + 0x20
BASELINE_VALUES = BASE + 0x24
OBSERVED_VALUES = BASE + 0x28
FUNCTIONAL_WRITE_COUNT = BASE + 0x2C
UNAUTHORIZED_WRITE_COUNT = BASE + 0x30
ERROR_COUNTS = BASE + 0x34
READBACK_VALUES = BASE + 0x38
ACTION_DESCRIPTOR = BASE + 0x3C
CAMPAIGN_STATE = BASE + 0x40
RESTORED_VALUES = BASE + 0x44
REJECTED_COMMAND_COUNT = BASE + 0x48
SANITY = BASE + 0x7C
SANITY_COUNT = BASE + 0x80

ACQ_PREPARE_BASELINE = 1
ACQ_DRYRUN_REWRITE_BASELINE = 2
ACQ_APPLY_SLICE_50 = 3
ACQ_APPLY_SLICE_40 = 4
ACQ_APPLY_SLICE_60 = 5
ACQ_ROLLBACK = 6
ACQ_ABORT_AND_ROLLBACK = 7

SANITY_TOKEN = 0x434F4D50

STATUS_IDLE = 1 << 0
STATUS_BUSY = 1 << 1
STATUS_DONE = 1 << 2
STATUS_HARD_FAIL = 1 << 3
STATUS_AUTOINIT_DONE = 1 << 4
STATUS_AUTOINIT_BUSY = 1 << 5
STATUS_I2C_OWNER = 1 << 6
STATUS_BANK_LOCKOUT = 1 << 7
STATUS_BASELINE_VALID = 1 << 14
STATUS_BASELINE_MISMATCH = 1 << 15
STATUS_DRYRUN_PASS = 1 << 18
STATUS_ROLLBACK_INVOKED = 1 << 19
STATUS_ROLLBACK_PASS = 1 << 20
STATUS_CAMPAIGN_CLOSED = 1 << 21
STATUS_SCANNER_BUSY = 1 << 22
STATUS_I2C_BUS_IDLE = 1 << 23

RESULT_NONE = 0x00
RESULT_PASS = 0x01
RESULT_REJECTED = 0x02
RESULT_FAILED_ROLLBACK_PASS = 0x03
RESULT_HARD_FAIL = 0xFF

CAPABILITY_NAMES = (
    "CH1_ONLY",
    "BANK5_0x05_0x08_ONLY",
    "PINNED_ORDER_0x08_THEN_0x05",
    "FULL_BYTE_BASELINE",
    "EXACT_ROLLBACK",
    "NO_GENERIC_I2C",
    "NO_MODE_WRITES",
    "NO_EQ_WRITES",
)

